= Neo4Art: Van Gogh's journey in a Neo4j graph DB

:neo4j-version: 2.0.0-RC1
:author: Lorenzo Speranzoni
:twitter: @inserpio
:tags: domain:art, use-case:van gogh's journey

== I. Preface 

Vincent Van Gogh is widely considered one of the most important neo-impressionist painters.

One fundamental aspect of his artwork was his continuous research for colours: "_during his early adulthood, while living between The Netherlands and Belgium, his palette consisted mainly of somber earth tones and showed no sign of the vivid coloration that distinguished his later work. In March 1886, he moved to Paris and discovered the French Impressionists. Later, he moved to the south of France and was influenced by the strong sunlight he found there. His work grew brighter in color, and he developed the unique and highly recognizable style that became fully realized during his stay in Arles in 1888_"

So how would I go about putting Van Gogh's journey into Neo4j?





== II. Introduction

First, I started with the data source: The http://www.vggallery.com/[*Vincent Van Gogh Gallery*] has a complete list of his paintings.

The root node is of course Vincent Van Gogh himself:

[source,cypher]
----
CREATE (van_gogh:ARTIST {first_name: 'Vincent', second_name: 'Willem', last_name: 'Van Gogh', born: 18530330, died: 18900729})

CREATE (van_gogh)-[:BORN_IN]->(zundert:CITY {name: 'Zundert', province: 'North Brabant', country: 'Netherland', latitude: 51.466667, longitude: 4.666667})

CREATE (van_gogh)-[:DIED_IN]->(auvers_sur_oise:CITY {name: 'Auvers-sur-Oise', region: 'Île-de-France', country: 'France', latitude: 49.0725, longitude: 2.175})

RETURN *
----

//graph

//console

