= Neo4Art: Van Gogh's journey in a Neo4j graph DB

== Preface 

Vincent Van Gogh is widely considered one of the most important neo-impressionist painters.

One fundamental aspect of his artwork was his continuous research for colours: “during his early adulthood, while living between The Netherlands and Belgium, his palette consisted mainly of somber earth tones and showed no sign of the vivid coloration that distinguished his later work. In March 1886, he moved to Paris and discovered the French Impressionists. Later, he moved to the south of France and was influenced by the strong sunlight he found there. His work grew brighter in color, and he developed the unique and highly recognizable style that became fully realized during his stay in Arles in 1888”

So how would I go about putting Van Gogh’s journey into Neo4j?

== Introduction

First, I started with the data source: The http://www.vggallery.com/[Vincent Van Gogh Gallery] has a complete list of his paintings.

The root node is of course Vincent Van Gogh himself:

[source,cypher]
----
CREATE (a:ARTIST {first_name: 'Vincent', second_name: 'Willem', last_name: 'Van Gogh', born: 18530330, died: 18900729})
----

Since I’ll access ARTIST nodes through its last_name property, I decided to introduce an unique index constraint:

[source,cypher]
----
CREATE CONSTRAINT ON (a:ARTIST) ASSERT a.last_name IS UNIQUE
----

Now, I’ll focus on CITIES and STAGES. First of all, where he was born and where he died:

[source,cypher]
----
MATCH (a:ARTIST {last_name: 'Van Gogh'}) CREATE (a)-[:BORN_IN]->(c:CITY {name: 'Zundert', province: 'North Brabant', country: 'Netherland', latitude: 51.466667, longitude: 4.666667})
MATCH (a:ARTIST {last_name: 'Van Gogh'}) CREATE (a)-[:DIED_IN]->(c:CITY {name: 'Auvers-sur-Oise', region: 'Île-de-France', country: 'France', latitude: 49.0725, longitude: 2.175})
----

Please note, we have a CITY with a province property and the other with a region property: Neo4j is schema-less (or, more correctly, “less schema”, as Jim Webber pointed out on his http://jimwebber.org/2014/01/starting-graph-databases-with-neo4j-2-0/[blog]).

Please also note that I’m saving latitude and longitude informations for future (maybe my next spike) geo-spatial queries: at present, I’m just supposing this is the correct way to store such kind of data.

Vincent Van Gogh adhered to the ‘Post-Impressionism’ art movement (more correctly, one of its founder):

[source,cypher]
----
MATCH (a:ARTIST {last_name: 'Van Gogh'}) CREATE (a)-[:BELONGS_TO]->(m:ART_MOVEMENT {name: 'Post-Impressionism', wikipedia: 'http://en.wikipedia.org/wiki/Post-Impressionism'})
----

Now I could write the first, very simple Cypher statement to look at nodes and relations I’ve just created:

//setup
//output
[source,cypher]
----
MATCH (art_movement:ART_MOVEMENT)<-[:BELONGS_TO]-(artist:ARTIST {last_name: 'Van Gogh'})-[r]->(city:CITY)
RETURN artist, art_movement, city
----

//graph









